<?php
/**
 * @File
 * Example custom module to add functionality in site information page.
 * @author Gagan David
 */

function example_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
 
  $dvalue = \Drupal::state()->get('siteapikey');
  if ($form_id == 'system_site_information_settings') {
      $form['api_key'] = [
        '#type' => 'tel',
        '#title' => 'Site API Key',
        '#attributes' => ['placeholder' => t('No API Key yet'),'id'=>'edit_site_information'],
        '#weight' => 1,
        '#default_value' =>$dvalue
        
      ];

    
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
             $form['actions'][$action]['#submit'][] = 'example_form_submit';
        }
      }

      if(!empty($dvalue))
      {
          $form['actions']['submit']['#value'] = t('Update Configation');
      }
  }
  return $form;
}

/*
*function for form submit to save api Key
*/
function example_form_submit($form,  $form_state) {
   $values = $form_state->cleanValues()->getValues();
  
   if(!empty($values['api_key']))
   {
     
     \Drupal::state()->set('siteapikey', $values['api_key']);
     $data = \Drupal::state()->get('siteapikey');
      \Drupal::messenger()->addStatus(t('Data Saved Successfully.'));
   }
 
  
}